spring:
  datasource:
  url: "jdbc:postgresql://localhost/teatime"
  username: "postgres"
  password: "123"
  jpa:
    generate-ddl: "false"
    show-sql: "false"
    hibernate:
      ddl-auto: "validate"
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: "true"
  mail:
    host: "smtp.yandex.ru"
    username: "bookshelfapp@ya.ru"
    password: "javaspring"
    port: "465"
    protocol: "smtps"
    debug: "true"

  session:
    jdbc:
      initialize-schema: "always"
      table-name: "SPRING_SESSION"